from pathlib import Path
from typing import Any, Dict


def _to_display(value: Any) -> str:
    if value is None:
        return "-"
    return str(value)


def generate_readme_env(schema: Dict[str, Any], output: Path) -> None:
    lines = [
        "# Environment Variables",
        "",
        "Generated by Envy. Keep this file committed for onboarding and deployment consistency.",
        "",
        "| Variable | Type | Required | Default | Sensitive | Description |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    variables = schema.get("variables", {})
    for key in sorted(variables.keys()):
        spec = variables[key]
        var_type = spec.get("type", "str")
        required = "yes" if spec.get("required", True) else "no"
        default = _to_display(spec.get("default"))
        sensitive = "yes" if spec.get("sensitive", False) else "no"
        description = str(spec.get("description", "")).replace("|", "\\|")
        lines.append(f"| {key} | {var_type} | {required} | {default} | {sensitive} | {description} |")

    output.write_text("\n".join(lines) + "\n", encoding="utf-8")